build.gradle
=> 라이브러리 업데이트

build.gradle, src/main/java/com/ss/heartlinkapi/login/config/SecurityConfig.java, src/main/java/com/ss/heartlinkapi/login/controller/LoginController.java, src/main/java/com/ss/heartlinkapi/login/dto/JoinDTO.java, src/main/java/com/ss/heartlinkapi/login/service/JoinService.java, src/main/java/com/ss/heartlinkapi/user/entity/ProfileEntity.java, src/main/java/com/ss/heartlinkapi/user/entity/Role.java, src/main/java/com/ss/heartlinkapi/user/entity/UserEntity.java, src/main/java/com/ss/heartlinkapi/user/repository/ProfileRepository.java, src/main/java/com/ss/heartlinkapi/user/repository/UserRepository.java
=> Featuer join

src/main/java/com/ss/heartlinkapi/login/controller/LoginController.java, src/main/java/com/ss/heartlinkapi/login/service/LoginService.java, src/main/java/com/ss/heartlinkapi/user/repository/UserRepository.java
=> feat: UserRepository 수정

src/main/java/com/ss/heartlinkapi/post/entity/PostEntity.java, src/main/java/com/ss/heartlinkapi/post/entity/Visibility.java, src/main/java/com/ss/heartlinkapi/user/entity/PostFileEntity.java
=> 게시글 엔티티 추가

src/main/java/com/ss/heartlinkapi/user/entity/UserEntity.java
=> chore: UserEntity수정

src/main/java/com/ss/heartlinkapi/login/jwt/LoginFilter.java
=> feat: LoginFilter 수정

src/main/java/com/ss/heartlinkapi/login/jwt/LoginFilter.java
=> chore:LoginFilter수정

src/main/java/com/ss/heartlinkapi/login/dto/CustomUserDetails.java
=> feat: CustomUserDetails 수정

src/main/java/com/ss/heartlinkapi/profile/controller/ProfileController.java
=> feat: ProfileController 수정

src/main/java/com/ss/heartlinkapi/profile/controller/ProfileController.java
=> chore:ProfileController 수정

src/main/java/com/ss/heartlinkapi/follow/controller/FollowController.java, src/main/java/com/ss/heartlinkapi/follow/dto/FollowerDTO.java, src/main/java/com/ss/heartlinkapi/follow/dto/FollowingDTO.java, src/main/java/com/ss/heartlinkapi/follow/repository/FollowRepository.java, src/main/java/com/ss/heartlinkapi/follow/service/FollowService.java
=> feat: Follow 리스트 반환 값 추가

src/main/java/com/ss/heartlinkapi/mainpage/controller/MainPageController.java, src/main/java/com/ss/heartlinkapi/mainpage/dto/UserCoupleDTO.java, src/main/java/com/ss/heartlinkapi/profile/dto/ProfileDTO.java
=> feat: Couple 정보조회 기능

src/main/java/com/ss/heartlinkapi/profile/controller/ProfileController.java, src/main/java/com/ss/heartlinkapi/profile/service/ProfileService.java
=> feat: 마이페이지 공개설정 기능 추가

src/main/java/com/ss/heartlinkapi/comment/repository/CommentRepository.java, src/main/java/com/ss/heartlinkapi/post/repository/PostRepository.java
=> feat: Repository 메서드 추가

src/main/java/com/ss/heartlinkapi/couple/service/CoupleService.java, src/main/java/com/ss/heartlinkapi/profile/controller/ProfileController.java, src/main/java/com/ss/heartlinkapi/profile/dto/ProfileDTO.java, src/main/java/com/ss/heartlinkapi/profile/service/ProfileService.java
프로필 조회기능 리펙토링 및 반환값에 비공개 여부 추가
=> refactor: 프로필 조회 리펙토링

src/main/java/com/ss/heartlinkapi/admin/service/AdminUserService.java, src/main/java/com/ss/heartlinkapi/follow/controller/FollowController.java, src/main/java/com/ss/heartlinkapi/follow/dto/FollowerDTO.java, src/main/java/com/ss/heartlinkapi/follow/dto/FollowingDTO.java, src/main/java/com/ss/heartlinkapi/follow/repository/FollowRepository.java, src/main/java/com/ss/heartlinkapi/follow/service/FollowService.java
팔로우, 팔로워 리스트 내에 반환값 상태메세지 추가 및 페이징 추가
=> feat: Follow 조회 수정

src/main/java/com/ss/heartlinkapi/block/controller/BlockController.java, src/main/java/com/ss/heartlinkapi/block/dto/BlockListDTO.java, src/main/java/com/ss/heartlinkapi/block/repository/BlockRepository.java, src/main/java/com/ss/heartlinkapi/block/service/BlockService.java, src/main/java/com/ss/heartlinkapi/follow/repository/FollowRepository.java
=> feat: Block리스트 반환 페이징 처리

src/main/java/com/ss/heartlinkapi/profile/controller/ProfileController.java, src/main/java/com/ss/heartlinkapi/profile/dto/ProfileDTO.java, src/main/java/com/ss/heartlinkapi/profile/service/ProfileService.java
로그인한 사용자가 해당 프로필 사용자를 팔로우 했는지 여부 반환, 팔로우 대기 상태인지 아닌지 반환 추가
=> feat: Profile 조회 반환 값 추가

src/main/java/com/ss/heartlinkapi/login/controller/LoginController.java, src/main/java/com/ss/heartlinkapi/login/service/LoginService.java
=> refactor: LoginService

src/main/java/com/ss/heartlinkapi/admin/controller/AdminCoupleMissionController.java
=> chore: AdminCoupleMissionController 수정

src/main/java/com/ss/heartlinkapi/images/ImagesController.java, src/main/java/com/ss/heartlinkapi/message/controller/MessageController.java
=> feat: ImagesController 분리

src/main/java/com/ss/heartlinkapi/mention/repository/MentionRepository.java, src/main/java/com/ss/heartlinkapi/post/controller/PostController.java, src/main/java/com/ss/heartlinkapi/post/dto/PostDTO.java, src/main/java/com/ss/heartlinkapi/post/service/PostService.java
Reverts tktkaj/heartlink-api#221
=> Revert "Feature/comment"

src/main/java/com/ss/heartlinkapi/mention/repository/MentionRepository.java, src/main/java/com/ss/heartlinkapi/post/controller/PostController.java, src/main/java/com/ss/heartlinkapi/post/dto/PostDTO.java, src/main/java/com/ss/heartlinkapi/post/service/PostService.java
Reverts tktkaj/heartlink-api#222
=> Revert "Revert "Feature/comment""

src/main/java/com/ss/heartlinkapi/comment/dto/CommentDTO.java, src/main/java/com/ss/heartlinkapi/like/repository/LikeRepository.java, src/main/java/com/ss/heartlinkapi/like/service/LikeService.java, src/main/java/com/ss/heartlinkapi/post/dto/PostDTO.java, src/main/java/com/ss/heartlinkapi/post/service/PostService.java
Reverts tktkaj/heartlink-api#227
=> Revert "Feature/feed write"
